name: lint
on: 
  push: 
    branches: [main]
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 17.9.0
      - name: Istall dependencies 
        - run: npm ci
      coverage:
        needs: [ test ]
        name: Run linter and tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@master
        - run: make install
        - run: make lint
        - run: make test
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 95b4a07ce2eded48123fbc39d260d8cf0ba67ce9207cd7b832a7c810531108ae
        with:
          coverageCommand: make test-coverage
          debug: true